### PR TITLE
Update plugin.py

### PR DESCRIPTION
**Pull request by lhitvietnam**
edit PowerStrip_Current, PowerStrip_Temperature

### CODE REVIEW

**Comment by xiaoyao9184** [comment]
@lhitvietnam What did this fix, I didn't understand.

**Comment by nefsolive** [comment]
It is possible to update the plugin to work with the 3C Purifier zhimi.airpurifier.mb4? I think python-miio have suport. Thanks

**Comment by nefsolive** [comment]
@xiaoyao9184 and @SylvainPer, hi I try use the plugin for 3C Purifier zhimi.airpurifier.mb4, but it doesn't work the best way! Is there anything you can add, since python miio is already supported?

**Comment by xiaoyao9184** [comment]
@nefsolive yep, need free time to do that.

**Comment by nefsolive** [comment]
@xiaoyao9184 Understand! Thank u ;)

**Comment by SylvainPer** [comment]
Can try to have a look, don't seem complicated but probably need support as I don't have a 3C.

The model line:
https://github.com/arturdobo/python-miio/blob/58b03d446146b70d8803adeb26098ea48fc87e39/miio/airpurifier_miot.py#L49

The new class:
https://github.com/arturdobo/python-miio/blob/58b03d446146b70d8803adeb26098ea48fc87e39/miio/airpurifier_miot.py#L499

Only ten elements !

**Comment by nefsolive** [comment]
@SylvainPer ty!
Yes, i was see model and class, and at moment i was create virtual dummy on domoticz and call scripts ex "On": 
#!/usr/bin/python3
import os
os.system("date")
os.system(' miiocli airpurifiermb4 --ip XXX.XXX.X.XXX --token xxxxxxxxxxxxxxxxxxxxxxxxx on')

and works great!

But it was diferent iff use plugin, like for see the status!

Regards

**Comment by SylvainPer** [comment]
@nefsolive could you give a try to this version : https://github.com/SylvainPer/DomoticzXiaomiPlugins/blob/master/MiioAirPurifierMiot/plugin.py
Thx

**Comment by nefsolive** [comment]
@SylvainPer Hello!
I already had the plugin installed! What I did was uninstall and install again with the command curl -L https://github.com/xiaoyao9184/DomoticzXiaomiPlugins/raw/master/install.sh | bash
I put all the ip and token parameters and added the dummys switch.
I tested the On / Off but the button does not activate!
I saw the log and got this error there;

`2021-03-26 11: 36: 49.180 Status: (Miio Air Purifier) Started.
2021-03-26 11: 36: 51.712 (Miio Air Purifier) Heartbeat total interval set to: 120.
2021-03-26 11: 36: 51.705 Status: (Miio Air Purifier) Entering work loop.
2021-03-26 11: 36: 51.706 Status: (Miio Air Purifier) Initialized version 0.1, author 'xiaoyao9184 SylvainPer'
2021-03-26 11: 36: 53.124 Error: (Miio Air Purifier) UpdateStatus: ValueError ('None is not a valid OperationMode')
2021-03-26 11: 36: 54.445 Error: (Miio Air Purifier) UpdateStatus: ValueError ('None is not a valid OperationMode')`
Thanks.

**Comment by SylvainPer** [comment]
Sorry, I didn't give you enough details.
I worked on my git for debug purpose.

Please proceed as following:
- remove the hardware in domoticz
- go in your domoticz directory in plugins/MiioAirPurifierMiot
- edit the plugin.py file and replace it by the content of https://github.com/SylvainPer/DomoticzXiaomiPlugins/blob/master/MiioAirPurifierMiot/plugin.py
- save the file
- restart domoticz
- add a new hardware like before and select in the new list "Purifier 3C"

Is that good for you ?

**Comment by nefsolive** [comment]
@SylvainPer ty
i go try again and comment the result!

**Comment by nefsolive** [comment]
@SylvainPer Yes now, it's running on the perfect 3C! 

Another great update on the plugin! 

Thank you for your help, attention and collaboration on this project! 

Great work!

**Comment by SylvainPer** [comment]
Great to hear.
Did you have a try on each elements ? 
I would like to know if the ten elements created are perfectly working before pushing the modifications.
Thanks

**Comment by nefsolive** [comment]
i try almout all! i will test all, and give u feedback.

**Comment by nefsolive** [comment]
Tested;

> Miio Purifier 3C - AirPurifier_Power - OK
> Miio Purifier 3C - AirPurifier_Buzzer - OK
> Miio Purifier 3C - AirPurifier_Child_Lock - OK
> Miio Purifier 3C - AirPurifier_Mode - Parameter "Fan" doesn´t work! But they dont need!  Auto, Favorite, and Silent working.
> Miio Purifier 3C - AirPurifier_Brightness - OK
> Miio Purifier 3C - AirPurifier_Motor_speed - OK
> Miio Purifier 3C - AirPurifier_AQI - Quality Air just show me 1ppm! I see more ppm, but did not update the value! Is it delay? 
> Miio Purifier 3C - AirPurifier_Filter_Hours_Used - I have houres value, need time for iff change value, but seems OK
> Miio Purifier 3C - AirPurifier_filter_life_remaining - I have % value, need time iff change value, but seems OK

I see this 9 elements created!

Thanks.

**Comment by SylvainPer** [comment]
You're rigth, only 9 elements.
Don't know why for the "Fan" level, it's working on my 3H and there is no difference in the library on that point.
Thanks for your return, I'll create a PR soon.

**Comment by nefsolive** [comment]
@SylvainPer, great too hear, yes "Fan" for 3C no difference!
My Miio Purifier 3C - AirPurifier_AQI, make a change now too 0 ppm! So I think everything is working well with a little delay.
I downloaded the value of the field "Repeat Time (s)" in the hardware and improved the delay. 

I also checked the graphics now , Miio Purifier 3C - AirPurifier_Filter_Hours_Used had changes, so everything is working fine!
 
Ty

**Comment by nefsolive** [comment]
@SylvainPer hi!
During these days of testing with the 3C, the AQI element is always at the value of 1ppm! 
I've been looking at the graph and it only shows 1ppm. 
It's normal? Or it doesn't seem to be working properly! 
Does 3H also happen?

The rest of the elements work perfectly!
Ty

**Comment by SylvainPer** [comment]
Mine is also to 1ppm almost every time on the screen and in domoticz.
Sometimes I have more but not very long, you can check by activating debug and look to the status response from the device.

**Comment by nefsolive** [comment]
Ok! Thank u for the feedback.
I go take a look!

**Comment by nefsolive** [comment]
@SylvainPer i activate debug, and the status: aqi i see the value change, like 'aqi=2', 'aqi=none', 'aqi=3' etc.
But on dummy aqi element, the value still 1ppm,not change! Some strange, dont think?

**Pull request closed without merging**
