### PR TITLE
Add the new model 3C

### PR DESCRIPTION
**Pull request by SylvainPer**
Need last miio library: https://pypi.org/project/python-miio/0.5.5.2/

### CODE REVIEW

**Comment by SylvainPer** [comment]
Thanks @nefsolive for the support.

**Comment by nefsolive** [comment]
Thank you @SylvainPer for everything!

**Comment by SylvainPer** [comment]
@nefsolive I pushed a correction, please update your version.
You need to remove the existing aqi device and relaunch the plugin

**Comment by nefsolive** [comment]
@SylvainPer Hi Ty for the support!
Follow your instructions.

- I try update the plugin with "git pull" but doesn´t work! 
- I installed it again with the command "curl -L https://github.com/xiaoyao9184/DomoticzXiaomiPlugins/raw/master/install.sh | bash", but in the plugin options i dont see the new list for choose "Purifier 3C"!
- So i edit the plugin.py file and replace it by the content of https://github.com/SylvainPer/DomoticzXiaomiPlugins/blob/master/MiioAirPurifierMiot/plugin.py
- save the file
- restart domoticz
- i remove aqi and relaunch plugin.
- On devices page i dont see the new aqi dummy!

Hardware page i delete plugin and reinstall again
Nothing, just show me 8 elements, not AQI!

Last day, wen we talk about AQI i try remove and update again plugin but i never see more the AQI element! So i do a backup for see again. But never the value works.

Maybe im not doing the update well! Something is missing!

**Comment by nefsolive** [comment]
@SylvainPer,
I revised the plugin code again and I didn't do it well! The element AQI already appears!
I will do the test if it already works and give my feedback.
Thank u!

**Comment by nefsolive** [comment]
@SylvainPer
I see this on my log;
`(Miio Purifier 3C - AQI) Updating device from 1:'248' to have values 1:'152'.` so on in log the value change.

But the value continues to show 1ppm on dummy (ex: graph) not change!
AQI

Of the 9 elements, this is the one that doesn't seem to want to work! :) But I want to thank you for your work and your help in trying to solve it.

**Comment by nefsolive** [comment]
@SylvainPer Finally!

I was reviewing the code again, and I verified that I was not putting your update in the right place! 

Now I already have the values ​​working, not in ppm, but in μg / m³ (for ppm i just need change ''Axis Label")

It's flawless! 💯 

Thanks for the dedication and help!
Best regards

**Comment by SylvainPer** [comment]
Sorry, made it quickly and forgot to give you the link to the file, I assumed you are familiar with github and you saw the modification just above my last comment.

@xiaoyao9184 could you accept the PR ? thanks

**Comment by nefsolive** [comment]
Hello, no problem! Yes, I know github for a while :) But I'm already seeing how it works.
Thanks and best regards.

**Comment by SylvainPer** [comment]
@xiaoyao9184 any remarks ?
I would like to close this subject please

**Comment by nefsolive** [comment]
@SylvainPer for me you can close!
Ty

**Comment by SylvainPer** [comment]
I need that @xiaoyao9184 merge the PR or I need to update my git if he's not supporting it anymore.

**Comment by SylvainPer** [comment]
Thank you !

**Pull request merged**
